/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tsapp.view;

import Entity.Employee;
import java.awt.event.ActionEvent;
import javax.swing.JFrame;
import tsapp.controller.Login_controller;

/**
 *
 * @author Huynh
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private Employee emp;
    private final Login_controller controller = new Login_controller();

    public Login() {
        initComponents();
        setErrorLabelVisible(false);
        actionListener();
    }

    private void setErrorLabelVisible(boolean error1) {
        errorLabel.setVisible(error1);
    }

    private void actionListener() {
        usernameTF.addActionListener((ActionEvent e) -> {
            Login();
        });

        passwdTF.addActionListener((ActionEvent e) -> {
            Login();
        });
        Loginbtn.addActionListener((ActionEvent e) -> {
            Login();
        });
    }

    private void Login() {

        emp = controller.getEmpLogin(usernameTF.getText(), passwdTF.getText());
//        emp = new Employee();
//        emp.setFullName("Quân Nguyễn");
//        emp.setAccRole("Role1");
//        emp.setID("NV3");
//        emp.setStatue(1);
        if (emp.getStatue() != 0) {
            setErrorLabelVisible(false);
            Main frame = new Main(emp);
            frame.setSize(1300, 760);
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setExtendedState(MAXIMIZED_BOTH);
            frame.setVisible(true);
            this.dispose();
        } else {
            setErrorLabelVisible(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        appnameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        passwdTF = new javax.swing.JPasswordField();
        errorLabel = new javax.swing.JLabel();
        Loginbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(25, 104, 192));
        setForeground(new java.awt.Color(51, 255, 0));
        setPreferredSize(new java.awt.Dimension(1300, 760));
        setSize(new java.awt.Dimension(1300, 760));

        jPanel1.setBackground(new java.awt.Color(25, 104, 192));
        jPanel1.setLayout(null);

        appnameLabel.setBackground(new java.awt.Color(25, 104, 192));
        appnameLabel.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
        appnameLabel.setText("QUẢN LÝ BÁN TRÀ SỮA");
        appnameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(appnameLabel);
        appnameLabel.setBounds(10, 10, 260, 30);

        jLabel1.setBackground(new java.awt.Color(25, 104, 192));
        jLabel1.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        jLabel1.setText("LOGIN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 120, 110, 40);

        loginPanel.setBackground(new java.awt.Color(204, 204, 255));
        loginPanel.setLayout(null);

        usernameLabel.setFont(new java.awt.Font("Myriad Pro", 0, 15)); // NOI18N
        usernameLabel.setText("Password:");
        loginPanel.add(usernameLabel);
        usernameLabel.setBounds(180, 130, 70, 20);

        passwordLabel.setFont(new java.awt.Font("Myriad Pro", 0, 15)); // NOI18N
        passwordLabel.setText("User name:");
        loginPanel.add(passwordLabel);
        passwordLabel.setBounds(180, 60, 90, 14);

        usernameTF.setFont(new java.awt.Font("Myriad Pro", 2, 15)); // NOI18N
        usernameTF.setForeground(new java.awt.Color(102, 102, 102));
        usernameTF.setText("huynhntn");
        loginPanel.add(usernameTF);
        usernameTF.setBounds(180, 80, 300, 30);

        passwdTF.setFont(new java.awt.Font("Myriad Pro", 2, 15)); // NOI18N
        passwdTF.setForeground(new java.awt.Color(102, 102, 102));
        passwdTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwdTFActionPerformed(evt);
            }
        });
        loginPanel.add(passwdTF);
        passwdTF.setBounds(180, 150, 300, 30);

        errorLabel.setFont(new java.awt.Font("Myriad Pro", 0, 11)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(102, 102, 102));
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        errorLabel.setText("Đăng nhập không thành công!");
        loginPanel.add(errorLabel);
        errorLabel.setBounds(180, 190, 300, 30);

        Loginbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bgButtonLogin.PNG"))); // NOI18N
        loginPanel.add(Loginbtn);
        Loginbtn.setBounds(250, 230, 150, 40);

        jPanel1.add(loginPanel);
        loginPanel.setBounds(370, 170, 650, 350);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwdTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwdTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwdTFActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Loginbtn;
    private javax.swing.JLabel appnameLabel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField passwdTF;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
